/**
 * Catálogo de productos del Contrato C-5/2025
 * Datos reales según especificaciones del contrato
 */

import { sub, add } from 'date-fns';
import type {
  ProductoC5,
  ComponenteKit,
  PedidoC5,
  GarantiaC5,
  ReparacionC5,
  MovimientoStockC5,
  KPIsContratoC5,
  AlertaC5,
  CONTRATO_C5_CONFIG,
} from './contrato-c5-types';

const today = new Date();

// ============================================
// EQUIPOS PRINCIPALES (Volumetría Máx: 200 uds cada uno)
// ============================================

export const equiposPrincipalesC5: ProductoC5[] = [
  {
    id: 'EP-001',
    sku: 'CA01-1524035M-X',
    nombre: 'Antena Tribanda',
    descripcion: 'Comunicaciones 3G/4G, WiFi y GPS',
    categoria: 'equipo_principal',
    stockMaximoContrato: 200,
    stockActual: 45,
    stockMinimo: 20,
    stockReservado: 10,
    requiereNumeroSerie: true,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'EP-002',
    sku: 'EX43008-00-I-AA',
    nombre: 'Switch Ethernet Industrial',
    descripcion: '10/100/1000, 8 puertos - EtherWAN',
    categoria: 'equipo_principal',
    stockMaximoContrato: 200,
    stockActual: 38,
    stockMinimo: 15,
    stockReservado: 5,
    requiereNumeroSerie: true,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'EP-003',
    sku: 'KIT-INT-001',
    nombre: 'Kit Integral Preinstalación',
    descripcion: 'Conjunto completo para bus - incluye todos los componentes',
    categoria: 'equipo_principal',
    stockMaximoContrato: 200,
    stockActual: 25,
    stockMinimo: 10,
    stockReservado: 8,
    requiereNumeroSerie: true,
    unidadMedida: 'ud',
    activo: true,
  },
];

// ============================================
// COMPONENTES DEL KIT INTEGRAL
// ============================================

export const componentesKitC5: ProductoC5[] = [
  // --- FUETONS ALARGADORES DE ANTENA ---
  {
    id: 'FK-001',
    sku: 'FUE-3G-1.5M',
    nombre: 'Fuetón 3G 1,5m',
    descripcion: 'Conector LTE a Harting',
    categoria: 'componente_kit',
    subcategoria: 'fueton_alargador',
    cantidadPorKit: 1,
    stockActual: 50,
    stockMinimo: 25,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'FK-002',
    sku: 'FUE-GPS-1.5M',
    nombre: 'Fuetón GPS 1,5m',
    descripcion: 'SMA-m a Harting',
    categoria: 'componente_kit',
    subcategoria: 'fueton_alargador',
    cantidadPorKit: 1,
    stockActual: 48,
    stockMinimo: 25,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'FK-003',
    sku: 'FUE-WIFI-1.5M',
    nombre: 'Fuetón WiFi 1,5m',
    descripcion: 'RP-SMA a Harting',
    categoria: 'componente_kit',
    subcategoria: 'fueton_alargador',
    cantidadPorKit: 1,
    stockActual: 52,
    stockMinimo: 25,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },

  // --- PLACA DE CONEXIONES (BORNER) ---
  {
    id: 'PL-001',
    sku: 'PLC-MONT-001',
    nombre: 'Placa de montaje',
    descripcion: 'Placa base para conexiones',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 30,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-002',
    sku: 'SOP-SWITCH-001',
    nombre: 'Soporte switch',
    descripcion: 'Soporte para switch ethernet',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 35,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-003',
    sku: 'PERF-OMEGA-001',
    nombre: 'Perfil omega para chapa',
    descripcion: 'Perfil omega para elementos de conexión',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 40,
    stockMinimo: 20,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-004',
    sku: 'CANAL-20X40',
    nombre: 'Canal 20x40',
    descripcion: 'Canal para cableado',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 45,
    stockMinimo: 20,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-005',
    sku: 'BORNA-FUS-2.5',
    nombre: 'Borna 2,5mm² con fusible',
    descripcion: 'Borna con protección por fusible',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 11,
    stockActual: 350,
    stockMinimo: 150,
    stockReservado: 88,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-006',
    sku: 'BORNA-DOB-2.5',
    nombre: 'Borna doble 2,5mm²',
    descripcion: 'Borna doble para conexiones',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 40,
    stockMinimo: 20,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-007',
    sku: 'BORNA-SIM-2.5',
    nombre: 'Borna simple 2,5mm²',
    descripcion: 'Borna simple para conexiones',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 10,
    stockActual: 320,
    stockMinimo: 150,
    stockReservado: 80,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-008',
    sku: 'BORNA-PROT-001',
    nombre: 'Borna protección',
    descripcion: 'Borna de protección a tierra',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 35,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-009',
    sku: 'PROT-TRANSIL',
    nombre: 'Protección transil',
    descripcion: 'Protector contra sobretensiones',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 28,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-010',
    sku: 'RELE-24V-20A',
    nombre: 'Relé 24V/20A',
    descripcion: 'Relé de potencia 24V 20A',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 2,
    stockActual: 65,
    stockMinimo: 30,
    stockReservado: 16,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-011',
    sku: 'BASE-RELE-001',
    nombre: 'Base de relé',
    descripcion: 'Base para montaje de relé',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 2,
    stockActual: 60,
    stockMinimo: 30,
    stockReservado: 16,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-012',
    sku: 'BORNA-SECC-001',
    nombre: 'Borna seccionador',
    descripcion: 'Borna con seccionador integrado',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 1,
    stockActual: 32,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'PL-013',
    sku: 'TOPE-BORNA-001',
    nombre: 'Topes',
    descripcion: 'Topes finales para bornas',
    categoria: 'componente_kit',
    subcategoria: 'placa_conexiones',
    cantidadPorKit: 7,
    stockActual: 230,
    stockMinimo: 100,
    stockReservado: 56,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },

  // --- CONTRA-CONECTOR MCC ---
  {
    id: 'CC-001',
    sku: 'MCC-4V-10M',
    nombre: 'Contra-conector MCC 4 vías',
    descripcion: 'Con manguera 10m incluida',
    categoria: 'componente_kit',
    subcategoria: 'contra_conector',
    cantidadPorKit: 1,
    stockActual: 28,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },

  // --- CONECTORES HARTING ---
  {
    id: 'HR-001',
    sku: 'HAN-16MOD-FLEX',
    nombre: 'Han 16Mod Andockrahmen flexibly',
    descripcion: 'Bastidor de acoplamiento flexible',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 1,
    stockActual: 30,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-002',
    sku: 'MOD-HEM-MULTI-A',
    nombre: 'Módulo hembra multicontacto - conector A',
    descripcion: 'Módulo multicontacto hembra',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 1,
    stockActual: 32,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-003',
    sku: 'HAN-DD-QUAD-BC',
    nombre: 'Han DD Quad module female',
    descripcion: 'Conectores B y C',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 1,
    stockActual: 28,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-004',
    sku: 'HAN-MOD-17DDD-D',
    nombre: 'Han Modular 17 DDD Module female',
    descripcion: 'Conector D',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 1,
    stockActual: 26,
    stockMinimo: 15,
    stockReservado: 8,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-005',
    sku: 'PIN-HAN-D-1.5',
    nombre: 'Pin hembra Han D 1,5mm',
    descripcion: 'Pin hembra para conector Han D',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 3,
    stockActual: 100,
    stockMinimo: 50,
    stockReservado: 24,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-006',
    sku: 'PIN-HAN-D-0.5',
    nombre: 'Pin hembra Han D 0,5mm',
    descripcion: 'Pin hembra para conector Han D',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 13,
    stockActual: 420,
    stockMinimo: 200,
    stockReservado: 104,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-007',
    sku: 'PIN-HAN-D-1.0',
    nombre: 'Pin hembra Han D 1mm',
    descripcion: 'Pin hembra para conector Han D',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 3,
    stockActual: 95,
    stockMinimo: 50,
    stockReservado: 24,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-008',
    sku: 'PIN-HAN-D-0.14',
    nombre: 'Pin hembra Han D 0,14/0,37mm',
    descripcion: 'Pin hembra para conector Han D fino',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 4,
    stockActual: 130,
    stockMinimo: 60,
    stockReservado: 32,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'HR-009',
    sku: 'FLOAT-WASH-M4',
    nombre: 'Float washer for M4 fixing screws',
    descripcion: 'Arandela flotante para tornillos M4',
    categoria: 'componente_kit',
    subcategoria: 'conector_harting',
    cantidadPorKit: 4,
    stockActual: 140,
    stockMinimo: 60,
    stockReservado: 32,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },

  // --- OTROS CABLES Y CONECTORES ---
  {
    id: 'OC-001',
    sku: 'CON-NEG-4V-VAL',
    nombre: 'Conector negro hembra 4 vías validadoras',
    descripcion: 'Conector de datos para validadoras',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 3,
    stockActual: 95,
    stockMinimo: 45,
    stockReservado: 24,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-002',
    sku: 'PIN-MACHO-4V',
    nombre: 'Pins macho conector 4 vías validadoras',
    descripcion: 'Pins macho de datos',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 12,
    stockActual: 380,
    stockMinimo: 180,
    stockReservado: 96,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-003',
    sku: 'RJ45-BLIND-CAT6',
    nombre: 'Conector macho blindado RJ-45 cat6',
    descripcion: 'Para cable flexible',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 4,
    stockActual: 130,
    stockMinimo: 60,
    stockReservado: 32,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-004',
    sku: 'FUNDA-RJ45-001',
    nombre: 'Funda conector RJ-45',
    descripcion: 'Funda protectora para RJ-45',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 4,
    stockActual: 140,
    stockMinimo: 60,
    stockReservado: 32,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-005',
    sku: 'MANG-ETH-FTP-40M',
    nombre: 'Manguera Ethernet FTP cat 6',
    descripcion: '40 metros por kit',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 40,
    stockActual: 1200,
    stockMinimo: 600,
    stockReservado: 320,
    requiereNumeroSerie: false,
    unidadMedida: 'm',
    activo: true,
  },
  {
    id: 'OC-006',
    sku: 'PORTAF-NEG-2.5',
    nombre: 'Portafusible negro con terminal faston 2,5mm',
    descripcion: 'Portafusibles con faston',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 2,
    stockActual: 65,
    stockMinimo: 30,
    stockReservado: 16,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-007',
    sku: 'TERM-FASTON-2.5',
    nombre: 'Terminal Faston hembra para cable 2,5mm',
    descripcion: 'Terminal faston hembra',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 4,
    stockActual: 130,
    stockMinimo: 60,
    stockReservado: 32,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-008',
    sku: 'FUS-15A-001',
    nombre: 'Fusible 15A para portafusibles',
    descripcion: 'Fusible de protección 15A',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 2,
    stockActual: 70,
    stockMinimo: 30,
    stockReservado: 16,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
  {
    id: 'OC-009',
    sku: 'PASAMUR-20MM',
    nombre: 'Pasamuros negros flexibles 20mm',
    descripcion: 'Pasamuros para cables',
    categoria: 'componente_kit',
    subcategoria: 'cables_conectores',
    cantidadPorKit: 6,
    stockActual: 195,
    stockMinimo: 90,
    stockReservado: 48,
    requiereNumeroSerie: false,
    unidadMedida: 'ud',
    activo: true,
  },
];

// Catálogo completo
export const catalogoProductosC5: ProductoC5[] = [
  ...equiposPrincipalesC5,
  ...componentesKitC5,
];

// ============================================
// COMPOSICIÓN DEL KIT INTEGRAL (para cálculos)
// ============================================

export const composicionKitIntegral: ComponenteKit[] = componentesKitC5.map(comp => ({
  productoId: comp.id,
  sku: comp.sku,
  nombre: comp.nombre,
  cantidadPorKit: comp.cantidadPorKit || 1,
  subcategoria: comp.subcategoria!,
}));

// ============================================
// DATOS MOCK PARA DESARROLLO
// ============================================

export const mockPedidosC5: PedidoC5[] = [
  // Grupo Direxis - TUSGSAL (346 vehículos - mayor operador)
  {
    id: 'ped-c5-001',
    codigo: 'PED-C5-2025-0001',
    operadorId: 'op-20',
    operadorNombre: 'TUSGSAL',
    estado: 'en_preparacion',
    fechaCreacion: sub(today, { days: 10 }),
    fechaConfirmacion: sub(today, { days: 8 }),
    fechaEntregaLimite: add(sub(today, { days: 8 }), { months: 3 }),
    lineas: [
      { id: 'lin-001', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 50, cantidadEntregada: 0 },
      { id: 'lin-002', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 50, cantidadEntregada: 0 },
      { id: 'lin-003', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 50, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Cotxera TUSGSAL, C/ Almogàvers 89, Badalona',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Avanza - UTE BAIX LLOBREGAT (205 vehículos)
  {
    id: 'ped-c5-002',
    codigo: 'PED-C5-2025-0002',
    operadorId: 'op-14',
    operadorNombre: 'UTE BAIX LLOBREGAT',
    estado: 'confirmado',
    fechaCreacion: sub(today, { days: 20 }),
    fechaConfirmacion: sub(today, { days: 18 }),
    fechaEntregaLimite: add(sub(today, { days: 18 }), { months: 3 }),
    lineas: [
      { id: 'lin-004', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 30, cantidadEntregada: 0 },
      { id: 'lin-005', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 30, cantidadEntregada: 0 },
      { id: 'lin-006', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 30, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Base Avanza Baix Llobregat, Sant Boi de Llobregat',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Moventia - MARFINA BUS (140 vehículos)
  {
    id: 'ped-c5-003',
    codigo: 'PED-C5-2025-0003',
    operadorId: 'op-28',
    operadorNombre: 'MARFINA BUS, SA - LA VALLESANA, SA',
    estado: 'entregado',
    fechaCreacion: sub(today, { days: 60 }),
    fechaConfirmacion: sub(today, { days: 58 }),
    fechaEntregaLimite: add(sub(today, { days: 58 }), { months: 3 }),
    fechaEntregaReal: sub(today, { days: 15 }),
    lineas: [
      { id: 'lin-007', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 20, cantidadEntregada: 20 },
      { id: 'lin-008', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 20, cantidadEntregada: 20 },
      { id: 'lin-009', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 20, cantidadEntregada: 20 },
    ],
    direccionEntrega: 'Cotxera Marfina, Polígon Industrial Can Magarola, Mollet del Vallès',
    creadoPor: 'admin@busembacat.com',
  },
  // Grupo Monbus - LA HISPANO IGUALADINA (121 vehículos)
  {
    id: 'ped-c5-004',
    codigo: 'PED-C5-2025-0004',
    operadorId: 'op-24',
    operadorNombre: 'LA HISPANO IGUALADINA, SL',
    estado: 'enviado',
    fechaCreacion: sub(today, { days: 25 }),
    fechaConfirmacion: sub(today, { days: 23 }),
    fechaEntregaLimite: add(sub(today, { days: 23 }), { months: 3 }),
    lineas: [
      { id: 'lin-010', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 15, cantidadEntregada: 0 },
      { id: 'lin-011', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 15, cantidadEntregada: 0 },
      { id: 'lin-012', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 15, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Cotxera Hispano Igualadina, Gabriel Castellà 7, Igualada',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Moventia - MOVENTIA L'HOSPITALET (117 vehículos)
  {
    id: 'ped-c5-005',
    codigo: 'PED-C5-2025-0005',
    operadorId: 'op-29',
    operadorNombre: 'MOVENTIA L\'HOSPITALET',
    estado: 'entregado',
    fechaCreacion: sub(today, { days: 45 }),
    fechaConfirmacion: sub(today, { days: 43 }),
    fechaEntregaLimite: add(sub(today, { days: 43 }), { months: 3 }),
    fechaEntregaReal: sub(today, { days: 5 }),
    lineas: [
      { id: 'lin-013', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 18, cantidadEntregada: 18 },
      { id: 'lin-014', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 18, cantidadEntregada: 18 },
      { id: 'lin-015', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 18, cantidadEntregada: 18 },
    ],
    direccionEntrega: 'Base Moventia, Carrer 60, 2, Sants-Montjuïc, L\'Hospitalet',
    creadoPor: 'admin@busembacat.com',
  },
  // Grupo Soler i Sauret - SOLER Y SAURET (109 vehículos)
  {
    id: 'ped-c5-006',
    codigo: 'PED-C5-2025-0006',
    operadorId: 'op-40',
    operadorNombre: 'SOLER Y SAURET, SA',
    estado: 'borrador',
    fechaCreacion: sub(today, { days: 2 }),
    lineas: [
      { id: 'lin-016', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 12, cantidadEntregada: 0 },
      { id: 'lin-017', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 12, cantidadEntregada: 0 },
      { id: 'lin-018', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 12, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Cotxera Soler i Sauret, Sant Feliu de Llobregat',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Sagalés - EMPRESA SAGALÉS (95 vehículos)
  {
    id: 'ped-c5-007',
    codigo: 'PED-C5-2025-0007',
    operadorId: 'op-35',
    operadorNombre: 'EMPRESA SAGALÉS, SA',
    estado: 'confirmado',
    fechaCreacion: sub(today, { days: 12 }),
    fechaConfirmacion: sub(today, { days: 10 }),
    fechaEntregaLimite: add(sub(today, { days: 10 }), { months: 3 }),
    lineas: [
      { id: 'lin-019', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 10, cantidadEntregada: 0 },
      { id: 'lin-020', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 10, cantidadEntregada: 0 },
      { id: 'lin-021', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 10, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Base Sagalés, Caldes de Montbui',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Empresa Plana - CINTOI BUS (85 vehículos)
  {
    id: 'ped-c5-008',
    codigo: 'PED-C5-2025-0008',
    operadorId: 'op-21',
    operadorNombre: 'CINTOI BUS, SL',
    estado: 'entregado_parcial',
    fechaCreacion: sub(today, { days: 40 }),
    fechaConfirmacion: sub(today, { days: 38 }),
    fechaEntregaLimite: add(sub(today, { days: 38 }), { months: 3 }),
    lineas: [
      { id: 'lin-022', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 10, cantidadEntregada: 6 },
      { id: 'lin-023', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 10, cantidadEntregada: 6 },
      { id: 'lin-024', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 10, cantidadEntregada: 6 },
    ],
    direccionEntrega: 'Cotxera Cintoi, Polígon Industrial El Garraf, Vilanova i la Geltrú',
    creadoPor: 'admin@busembacat.com',
  },
  // Independiente - TUS, SCCL (70 vehículos)
  {
    id: 'ped-c5-009',
    codigo: 'PED-C5-2025-0009',
    operadorId: 'op-13',
    operadorNombre: 'TUS, SCCL',
    estado: 'entregado',
    fechaCreacion: sub(today, { days: 55 }),
    fechaConfirmacion: sub(today, { days: 53 }),
    fechaEntregaLimite: add(sub(today, { days: 53 }), { months: 3 }),
    fechaEntregaReal: sub(today, { days: 8 }),
    lineas: [
      { id: 'lin-025', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 8, cantidadEntregada: 8 },
      { id: 'lin-026', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 8, cantidadEntregada: 8 },
      { id: 'lin-027', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 8, cantidadEntregada: 8 },
    ],
    direccionEntrega: 'Cotxera TUS, Sabadell',
    creadoPor: 'sermetra@busembacat.com',
  },
  // Grupo Avanza - TMESA (71 vehículos)
  {
    id: 'ped-c5-010',
    codigo: 'PED-C5-2025-0010',
    operadorId: 'op-17',
    operadorNombre: 'TMESA',
    estado: 'en_preparacion',
    fechaCreacion: sub(today, { days: 8 }),
    fechaConfirmacion: sub(today, { days: 6 }),
    fechaEntregaLimite: add(sub(today, { days: 6 }), { months: 3 }),
    lineas: [
      { id: 'lin-028', productoId: 'EP-001', sku: 'CA01-1524035M-X', nombre: 'Antena Tribanda', cantidadPedida: 10, cantidadEntregada: 0 },
      { id: 'lin-029', productoId: 'EP-002', sku: 'EX43008-00-I-AA', nombre: 'Switch Ethernet Industrial', cantidadPedida: 10, cantidadEntregada: 0 },
      { id: 'lin-030', productoId: 'EP-003', sku: 'KIT-INT-001', nombre: 'Kit Integral Preinstalación', cantidadPedida: 10, cantidadEntregada: 0 },
    ],
    direccionEntrega: 'Cotxera TMESA, Terrassa',
    creadoPor: 'sermetra@busembacat.com',
  },
];

export const mockGarantiasC5: GarantiaC5[] = [
  // Garantías de equipos entregados a MARFINA BUS (Moventia)
  {
    id: 'gar-001',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2025-00001',
    fechaEntrega: sub(today, { days: 15 }),
    fechaFinGarantia: add(sub(today, { days: 15 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-MRF-3001',
    operadorId: 'op-28',
    operadorNombre: 'MARFINA BUS, SA - LA VALLESANA, SA',
  },
  {
    id: 'gar-002',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2025-00001',
    fechaEntrega: sub(today, { days: 15 }),
    fechaFinGarantia: add(sub(today, { days: 15 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-MRF-3001',
    operadorId: 'op-28',
    operadorNombre: 'MARFINA BUS, SA - LA VALLESANA, SA',
  },
  {
    id: 'gar-003',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    numeroSerie: 'KIT-2025-00001',
    fechaEntrega: sub(today, { days: 15 }),
    fechaFinGarantia: add(sub(today, { days: 15 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-MRF-3001',
    operadorId: 'op-28',
    operadorNombre: 'MARFINA BUS, SA - LA VALLESANA, SA',
  },
  // Garantías de equipos entregados a MOVENTIA L'HOSPITALET
  {
    id: 'gar-004',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2025-00020',
    fechaEntrega: sub(today, { days: 5 }),
    fechaFinGarantia: add(sub(today, { days: 5 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-MVT-1101',
    operadorId: 'op-29',
    operadorNombre: 'MOVENTIA L\'HOSPITALET',
  },
  {
    id: 'gar-005',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2025-00020',
    fechaEntrega: sub(today, { days: 5 }),
    fechaFinGarantia: add(sub(today, { days: 5 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-MVT-1101',
    operadorId: 'op-29',
    operadorNombre: 'MOVENTIA L\'HOSPITALET',
  },
  // Garantías de equipos entregados a TUS, SCCL
  {
    id: 'gar-006',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2025-00040',
    fechaEntrega: sub(today, { days: 8 }),
    fechaFinGarantia: add(sub(today, { days: 8 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-TUS-0816',
    operadorId: 'op-13',
    operadorNombre: 'TUS, SCCL',
  },
  {
    id: 'gar-007',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2025-00040',
    fechaEntrega: sub(today, { days: 8 }),
    fechaFinGarantia: add(sub(today, { days: 8 }), { months: 24 }),
    estado: 'vigente',
    vehiculoInstalado: 'VEH-TUS-0816',
    operadorId: 'op-13',
    operadorNombre: 'TUS, SCCL',
  },
  // Garantías PRÓXIMAS A VENCER (equipos instalados hace 22 meses)
  {
    id: 'gar-008',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2023-00050',
    fechaEntrega: sub(today, { months: 22 }),
    fechaFinGarantia: add(sub(today, { months: 22 }), { months: 24 }),
    estado: 'proxima_vencer',
    vehiculoInstalado: 'VEH-TGS-2001',
    operadorId: 'op-20',
    operadorNombre: 'TUSGSAL',
  },
  {
    id: 'gar-009',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2023-00050',
    fechaEntrega: sub(today, { months: 22 }),
    fechaFinGarantia: add(sub(today, { months: 22 }), { months: 24 }),
    estado: 'proxima_vencer',
    vehiculoInstalado: 'VEH-TGS-2001',
    operadorId: 'op-20',
    operadorNombre: 'TUSGSAL',
  },
  {
    id: 'gar-010',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2023-00055',
    fechaEntrega: sub(today, { months: 23 }),
    fechaFinGarantia: add(sub(today, { months: 23 }), { months: 24 }),
    estado: 'proxima_vencer',
    vehiculoInstalado: 'VEH-HIG-5001',
    operadorId: 'op-24',
    operadorNombre: 'LA HISPANO IGUALADINA, SL',
  },
  // Garantía RECLAMADA
  {
    id: 'gar-011',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    numeroSerie: 'KIT-2024-00088',
    fechaEntrega: sub(today, { months: 10 }),
    fechaFinGarantia: add(sub(today, { months: 10 }), { months: 24 }),
    estado: 'reclamada',
    vehiculoInstalado: 'VEH-SAG-4001',
    operadorId: 'op-35',
    operadorNombre: 'EMPRESA SAGALÉS, SA',
    rmasAsociados: ['rep-004'],
  },
  // Garantías VENCIDAS
  {
    id: 'gar-012',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2022-00010',
    fechaEntrega: sub(today, { months: 30 }),
    fechaFinGarantia: add(sub(today, { months: 30 }), { months: 24 }),
    estado: 'vencida',
    vehiculoInstalado: 'VEH-SSR-6001',
    operadorId: 'op-40',
    operadorNombre: 'SOLER Y SAURET, SA',
  },
];

export const mockReparacionesC5: ReparacionC5[] = [
  // Reparación EN CURSO - TUSGSAL (Direxis) - Avería
  {
    id: 'rep-001',
    codigo: 'REP-C5-2025-0001',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2024-00088',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Pérdida de señal GPS intermitente',
    estado: 'en_reparacion',
    fechaReporte: sub(today, { days: 3 }),
    fechaLimiteSLA: add(sub(today, { days: 3 }), { days: 7 }),
    diasTranscurridos: 3,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-TGS-2045',
    operadorId: 'op-20',
    operadorNombre: 'TUSGSAL',
    asignadoA: 'tecnico@busembacat.com',
  },
  // Reparación EN DIAGNÓSTICO - UTE BAIX LLOBREGAT (Avanza) - Vandalismo
  {
    id: 'rep-002',
    codigo: 'REP-C5-2025-0002',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2024-00045',
    tipoIncidencia: 'vandalismo',
    slaDias: 15,
    descripcion: 'Carcasa rota por impacto, puertos dañados',
    estado: 'en_diagnostico',
    fechaReporte: sub(today, { days: 5 }),
    fechaLimiteSLA: add(sub(today, { days: 5 }), { days: 15 }),
    diasTranscurridos: 5,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-BLL-1205',
    operadorId: 'op-14',
    operadorNombre: 'UTE BAIX LLOBREGAT',
    evidencias: [
      { id: 'ev-001', tipo: 'foto', url: '/evidencias/rep-002-1.jpg', descripcion: 'Carcasa dañada', fecha: sub(today, { days: 5 }), subidoPor: 'operador@busembacat.com' },
      { id: 'ev-002', tipo: 'foto', url: '/evidencias/rep-002-2.jpg', descripcion: 'Puertos dañados', fecha: sub(today, { days: 5 }), subidoPor: 'operador@busembacat.com' },
    ],
    asignadoA: 'tecnico@busembacat.com',
  },
  // Reparación CERRADA - LA HISPANO IGUALADINA (Monbus)
  {
    id: 'rep-003',
    codigo: 'REP-C5-2025-0003',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    numeroSerie: 'KIT-2024-00022',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Fallo en conectores Harting - no hace contacto',
    estado: 'cerrada',
    fechaReporte: sub(today, { days: 15 }),
    fechaLimiteSLA: add(sub(today, { days: 15 }), { days: 7 }),
    fechaResolucion: sub(today, { days: 10 }),
    diasTranscurridos: 5,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-HIG-5012',
    operadorId: 'op-24',
    operadorNombre: 'LA HISPANO IGUALADINA, SL',
    diagnostico: 'Conector con defecto de fábrica en pines',
    accionCorrectiva: 'Sustituido por unidad nueva',
    numeroSerieSustitucion: 'KIT-2025-00005',
    asignadoA: 'tecnico@busembacat.com',
  },
  // Reparación ABIERTA - EMPRESA SAGALÉS (Sagalés) - Reclamación garantía
  {
    id: 'rep-004',
    codigo: 'REP-C5-2025-0004',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    numeroSerie: 'KIT-2024-00088',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Cortocircuito en placa de conexiones - bajo garantía',
    estado: 'abierta',
    fechaReporte: sub(today, { days: 1 }),
    fechaLimiteSLA: add(sub(today, { days: 1 }), { days: 7 }),
    diasTranscurridos: 1,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-SAG-4001',
    operadorId: 'op-35',
    operadorNombre: 'EMPRESA SAGALÉS, SA',
    garantiaRef: 'gar-011',
    asignadoA: 'tecnico@busembacat.com',
  },
  // Reparación EN RIESGO SLA - MOVENTIA L'HOSPITALET
  {
    id: 'rep-005',
    codigo: 'REP-C5-2025-0005',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2024-00112',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Antena no recibe señal WiFi',
    estado: 'en_reparacion',
    fechaReporte: sub(today, { days: 5 }),
    fechaLimiteSLA: add(sub(today, { days: 5 }), { days: 7 }),
    diasTranscurridos: 5,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-MVT-1108',
    operadorId: 'op-29',
    operadorNombre: 'MOVENTIA L\'HOSPITALET',
    diagnostico: 'Módulo WiFi defectuoso - requiere sustitución',
    asignadoA: 'tecnico2@busembacat.com',
  },
  // Reparación CERRADA - SOLER Y SAURET - Vandalismo
  {
    id: 'rep-006',
    codigo: 'REP-C5-2025-0006',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    numeroSerie: 'SWT-2024-00078',
    tipoIncidencia: 'vandalismo',
    slaDias: 15,
    descripcion: 'Switch arrancado del soporte por acto vandálico',
    estado: 'cerrada',
    fechaReporte: sub(today, { days: 20 }),
    fechaLimiteSLA: add(sub(today, { days: 20 }), { days: 15 }),
    fechaResolucion: sub(today, { days: 8 }),
    diasTranscurridos: 12,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-SSR-6025',
    operadorId: 'op-40',
    operadorNombre: 'SOLER Y SAURET, SA',
    diagnostico: 'Daño físico irreparable',
    accionCorrectiva: 'Sustituido por unidad nueva',
    numeroSerieSustitucion: 'SWT-2025-00015',
    evidencias: [
      { id: 'ev-003', tipo: 'foto', url: '/evidencias/rep-006-1.jpg', descripcion: 'Soporte dañado', fecha: sub(today, { days: 20 }), subidoPor: 'operador@busembacat.com' },
    ],
    asignadoA: 'tecnico@busembacat.com',
  },
  // Reparación REPARADA pendiente devolución - CINTOI BUS
  {
    id: 'rep-007',
    codigo: 'REP-C5-2025-0007',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    numeroSerie: 'ANT-2024-00095',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Pérdida total de señal 4G',
    estado: 'reparado',
    fechaReporte: sub(today, { days: 6 }),
    fechaLimiteSLA: add(sub(today, { days: 6 }), { days: 7 }),
    fechaResolucion: sub(today, { days: 1 }),
    diasTranscurridos: 5,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-CIN-2015',
    operadorId: 'op-21',
    operadorNombre: 'CINTOI BUS, SL',
    diagnostico: 'Amplificador LTE dañado',
    accionCorrectiva: 'Reparado - sustituido amplificador interno',
    asignadoA: 'tecnico2@busembacat.com',
  },
  // Reparación EN DIAGNÓSTICO - TMESA (Avanza)
  {
    id: 'rep-008',
    codigo: 'REP-C5-2025-0008',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    numeroSerie: 'KIT-2024-00055',
    tipoIncidencia: 'averia',
    slaDias: 7,
    descripcion: 'Fallo intermitente en comunicación Ethernet',
    estado: 'en_diagnostico',
    fechaReporte: sub(today, { days: 2 }),
    fechaLimiteSLA: add(sub(today, { days: 2 }), { days: 7 }),
    diasTranscurridos: 2,
    cumpleSLA: true,
    vehiculoOrigen: 'VEH-TMS-3045',
    operadorId: 'op-17',
    operadorNombre: 'TMESA',
    asignadoA: 'tecnico@busembacat.com',
  },
];

export const mockMovimientosC5: MovimientoStockC5[] = [
  // Entradas de stock inicial
  {
    id: 'mov-001',
    tipo: 'entrada_stock',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 100,
    fecha: sub(today, { days: 60 }),
    realizadoPor: 'admin@busembacat.com',
    notas: 'Recepción lote inicial contrato C5-2025',
  },
  {
    id: 'mov-002',
    tipo: 'entrada_stock',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    cantidad: 80,
    fecha: sub(today, { days: 60 }),
    realizadoPor: 'admin@busembacat.com',
    notas: 'Recepción lote inicial contrato C5-2025',
  },
  {
    id: 'mov-003',
    tipo: 'entrada_stock',
    productoId: 'EP-003',
    productoNombre: 'Kit Integral Preinstalación',
    cantidad: 60,
    fecha: sub(today, { days: 60 }),
    realizadoPor: 'admin@busembacat.com',
    notas: 'Recepción lote inicial contrato C5-2025',
  },
  // Reservas para pedidos
  {
    id: 'mov-004',
    tipo: 'reserva_pedido',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 50,
    pedidoRef: 'ped-c5-001',
    fecha: sub(today, { days: 8 }),
    realizadoPor: 'sermetra@busembacat.com',
    notas: 'Reserva para TUSGSAL',
  },
  {
    id: 'mov-005',
    tipo: 'reserva_pedido',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 30,
    pedidoRef: 'ped-c5-002',
    fecha: sub(today, { days: 18 }),
    realizadoPor: 'sermetra@busembacat.com',
    notas: 'Reserva para UTE BAIX LLOBREGAT',
  },
  // Salidas por instalación - MARFINA BUS
  {
    id: 'mov-006',
    tipo: 'salida_instalacion',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 20,
    numeroSerie: 'ANT-2025-00001 a ANT-2025-00020',
    vehiculoRef: 'Lote VEH-MRF-3001 a VEH-MRF-3020',
    operadorId: 'op-28',
    fecha: sub(today, { days: 15 }),
    realizadoPor: 'instalador@busembacat.com',
    notas: 'Instalación en flota MARFINA BUS',
  },
  {
    id: 'mov-007',
    tipo: 'salida_instalacion',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    cantidad: 20,
    numeroSerie: 'SWT-2025-00001 a SWT-2025-00020',
    vehiculoRef: 'Lote VEH-MRF-3001 a VEH-MRF-3020',
    operadorId: 'op-28',
    fecha: sub(today, { days: 15 }),
    realizadoPor: 'instalador@busembacat.com',
    notas: 'Instalación en flota MARFINA BUS',
  },
  // Salidas por instalación - MOVENTIA L'HOSPITALET
  {
    id: 'mov-008',
    tipo: 'salida_instalacion',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 18,
    numeroSerie: 'ANT-2025-00021 a ANT-2025-00038',
    vehiculoRef: 'Lote VEH-MVT-1101 a VEH-MVT-1118',
    operadorId: 'op-29',
    fecha: sub(today, { days: 5 }),
    realizadoPor: 'instalador@busembacat.com',
    notas: 'Instalación en flota MOVENTIA L\'HOSPITALET',
  },
  // Salidas por instalación - TUS, SCCL
  {
    id: 'mov-009',
    tipo: 'salida_instalacion',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 8,
    numeroSerie: 'ANT-2025-00039 a ANT-2025-00046',
    vehiculoRef: 'Lote VEH-TUS-0816 a VEH-TUS-0823',
    operadorId: 'op-13',
    fecha: sub(today, { days: 8 }),
    realizadoPor: 'instalador@busembacat.com',
    notas: 'Instalación en flota TUS, SCCL',
  },
  // Devolución para reparación
  {
    id: 'mov-010',
    tipo: 'devolucion_reparacion',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 1,
    numeroSerie: 'ANT-2024-00088',
    vehiculoRef: 'VEH-TGS-2045',
    operadorId: 'op-20',
    fecha: sub(today, { days: 3 }),
    realizadoPor: 'operador@busembacat.com',
    notas: 'Recogida para reparación - Pérdida señal GPS',
  },
  {
    id: 'mov-011',
    tipo: 'devolucion_reparacion',
    productoId: 'EP-002',
    productoNombre: 'Switch Ethernet Industrial',
    cantidad: 1,
    numeroSerie: 'SWT-2024-00045',
    vehiculoRef: 'VEH-BLL-1205',
    operadorId: 'op-14',
    fecha: sub(today, { days: 5 }),
    realizadoPor: 'operador@busembacat.com',
    notas: 'Recogida por vandalismo - carcasa rota',
  },
  // Entrada reposición stock
  {
    id: 'mov-012',
    tipo: 'entrada_stock',
    productoId: 'EP-001',
    productoNombre: 'Antena Tribanda',
    cantidad: 30,
    fecha: sub(today, { days: 10 }),
    realizadoPor: 'admin@busembacat.com',
    notas: 'Reposición stock - segundo lote',
  },
];

export const mockAlertasC5: AlertaC5[] = [
  {
    id: 'alerta-001',
    tipo: 'garantia_proxima_vencer',
    nivel: 'warning',
    titulo: 'Garantía próxima a vencer - TUSGSAL',
    descripcion: 'Antena Tribanda ANT-2023-00050 vence en 60 días (VEH-TGS-2001)',
    entidadRef: 'gar-008',
    fecha: today,
    leida: false,
  },
  {
    id: 'alerta-002',
    tipo: 'garantia_proxima_vencer',
    nivel: 'warning',
    titulo: 'Garantía próxima a vencer - LA HISPANO IGUALADINA',
    descripcion: 'Antena Tribanda ANT-2023-00055 vence en 30 días (VEH-HIG-5001)',
    entidadRef: 'gar-010',
    fecha: today,
    leida: false,
  },
  {
    id: 'alerta-003',
    tipo: 'reparacion_sla_riesgo',
    nivel: 'warning',
    titulo: 'Reparación cerca del SLA - MOVENTIA',
    descripcion: 'REP-C5-2025-0005: 2 días restantes para cumplir SLA (Antena WiFi)',
    entidadRef: 'rep-005',
    fecha: today,
    leida: false,
  },
  {
    id: 'alerta-004',
    tipo: 'stock_bajo',
    nivel: 'info',
    titulo: 'Stock Kit Integral bajo mínimo',
    descripcion: 'Kit Integral Preinstalación: 25 uds en stock (mínimo: 10)',
    entidadRef: 'EP-003',
    fecha: sub(today, { days: 1 }),
    leida: true,
  },
  {
    id: 'alerta-005',
    tipo: 'entrega_pendiente',
    nivel: 'info',
    titulo: 'Pedido pendiente envío - TUSGSAL',
    descripcion: 'PED-C5-2025-0001: 50 kits en preparación para TUSGSAL',
    entidadRef: 'ped-c5-001',
    fecha: sub(today, { days: 2 }),
    leida: true,
  },
];

export const mockKPIsC5: KPIsContratoC5 = {
  // Stock - basado en 2353 vehículos totales
  equiposPrincipalesEnStock: 142, // 45 antenas + 38 switches + 25 kits + stock reposición
  equiposPrincipalesInstalados: 98, // 20+18+8+... de los pedidos entregados
  componentesConStockBajo: 2,
  porcentajeStockUsado: 24, // 142 de 600 (200 x 3 tipos)

  // Pedidos - 10 pedidos activos
  pedidosPendientes: 6,
  pedidosEntregadosEnPlazo: 4,
  pedidosTotales: 10,

  // Garantías - 12 garantías
  garantiasVigentes: 9,
  garantiasProximasVencer: 3,

  // Reparaciones - 8 reparaciones
  reparacionesAbiertas: 5,
  reparacionesEnSLA: 7,
  reparacionesFueraSLA: 1,
  tiempoMedioReparacionDias: 4.5,

  fechaActualizacion: today,
};
